try :
  a = 345/9
except Exception as e:
  print(e) 
else: # gets executed when there 
  # is no error in the try block
  print("Hey! I am good")   
